package kr.nanoit.dto.login;

import kr.nanoit.dto.message_Structure.IndexHeader;

/**
 * The type Index login ack.
 */
public class IndexLoginAck {
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_RESULT_CODE.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_RESULT_CODE = IndexHeader.INDEX_HEADER_FULL_LENGTH;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_SMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_SMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_RESULT_CODE + LengthLoginAck.LENGTH_LOGIN_ACK_RESULT_CODE;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_LMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_LMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_SMS_TPS + LengthLoginAck.LENGTH_LOGIN_ACK_SMS_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_MMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_MMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_LMS_TPS + LengthLoginAck.LENGTH_LOGIN_ACK_LMS_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KAT_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KAT_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_MMS_TPS + LengthLoginAck.LENGTH_LOGIN_ACK_MMS_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KFT_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KFT_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KAT_TPS + LengthLoginAck.LENGTH_LOGIN_ACK_KAT_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_GMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_GMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KFT_TPS + LengthLoginAck.LENGTH_LOGIN_ACK_KFT_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_FULL.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_FULL = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_GMS_TPS + LengthLoginAck.LENGTH_LOGIN_ACK_GMS_TPS;
}