package kr.nanoit.dto.send;


import kr.nanoit.dto.message_Structure.IndexHeader;

/**
 * The type Index send ack.
 */
public class IndexSendAck {
    /**
     * The constant BIZ_INDEX_SEND_ACKNOWLEDGEMENT_RESULT_CODE.
     */
    public static int INDEX_SEND_ACKNOWLEDGEMENT_RESULT_CODE = IndexHeader.INDEX_HEADER_FULL_LENGTH;
    /**
     * The constant BIZ_INDEX_SEND_ACKNOWLEDGEMENT_MESSAGE_TYPE.
     */
    public static int INDEX_SEND_ACKNOWLEDGEMENT_MESSAGE_TYPE = INDEX_SEND_ACKNOWLEDGEMENT_RESULT_CODE + LengthSendAck.LENGTH_SEND_ACKNOWLEDGEMENT_RESULT_CODE;
    /**
     * The constant BIZ_INDEX_SEND_ACKNOWLEDGEMENT_MESSAGE_ID.
     */
    public static int INDEX_SEND_ACKNOWLEDGEMENT_MESSAGE_ID = INDEX_SEND_ACKNOWLEDGEMENT_MESSAGE_TYPE + LengthSendAck.LENGTH_SEND_ACKNOWLEDGEMENT_MESSAGE_TYPE;
    /**
     * The constant BIZ_INDEX_SEND_ACKNOWLEDGEMENT_LENGTH.
     */
    public static int BIZ_INDEX_SEND_ACKNOWLEDGEMENT_LENGTH = INDEX_SEND_ACKNOWLEDGEMENT_MESSAGE_ID + LengthSendAck.LENGTH_SEND_ACKNOWLEDGEMENT_MESSAGE_ID;
}